package com.vgg.vggcodechallenge.entities;
// Generated 08-Feb-2020 23:40:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Actions generated by hbm2java
 */
@Entity
@Table(name="actions"
)
public class Actions  implements java.io.Serializable {


     private Integer id;
     private Projects projects;
     private String description;
     private String note;

    public Actions() {
    }

	
    public Actions(Integer id, String description, String note) {
        this.id = id;
        this.description = description;
        this.note = note;
    }
    public Actions(Integer id, Projects projects, String description, String note) {
       this.id = id;
       this.projects = projects;
       this.description = description;
       this.note = note;
    }
   
     @Id 

    
    @Column(name="id")
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_id")
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }

    
    @Column(name="description", nullable=false, length=2000000000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="note", nullable=false, length=2000000000)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


