package com.vgg.vggcodechallenge.entities;
// Generated 08-Feb-2020 23:40:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name="projects"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Projects  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Integer completed;
     private Set actionses = new HashSet(0);

    public Projects() {
    }

	
    public Projects(Integer id, String name, String description) {
        this.id = id;
        this.name = name;
        this.description = description;
    }
    public Projects(Integer id, String name, String description, Integer completed, Set actionses) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.completed = completed;
       this.actionses = actionses;
    }
   
     @Id 

    
    @Column(name="id")
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=2000000000)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false, length=2000000000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="completed")
    public Integer getCompleted() {
        return this.completed;
    }
    
    public void setCompleted(Integer completed) {
        this.completed = completed;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="projects")
    public Set getActionses() {
        return this.actionses;
    }
    
    public void setActionses(Set actionses) {
        this.actionses = actionses;
    }




}


